name: study_academy
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.7
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  image_picker: ^1.1.2
  # network_info_plus: ^6.0.1
  no_screenshot: ^0.2.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
