name: study_academy
description: "A new Flutter project."
publish_to: 'none'

version: 3.5.2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cached_network_image: ^3.2.1
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  # equatable: ^2.0.5
  file_picker: ^8.0.7
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  # flutter_bloc: ^8.1.6
  flutter_riverpod: ^2.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  # network_info_plus: ^6.0.1
  just_audio: ^0.9.40
  no_screenshot: ^0.2.0
  # flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  permission_handler: ^9.2.0
  audioplayers: ^1.0.1
  swipe_to: ^1.0.2
  pdf: ^3.11.1
  # permission_handler: ^11.3.1
  # record: ^5.1.2
  url_launcher: ^6.3.0
  uuid: ^3.0.6
  video_player: ^2.6.0
  cached_video_player_plus: ^3.0.3
  flutter_cached_pdfview: ^0.4.2
  flutter_pdfview: 1.3.2
  flick_video_player: ^0.9.0
  flutter_sound_record: ^3.3.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
