name: study_academy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  chewie: ^1.8.3
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.3
  flick_video_player: ^0.9.0
  flutter:
    sdk: flutter
  # flutter_windowmanager: ^0.2.0
  flutter_cache_manager: ^3.4.1
  flutter_cached_pdfview: ^0.4.2
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  no_screenshot: ^0.2.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  video_player: ^2.9.1
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.6
  webview_flutter_platform_interface: ^2.10.0
  webview_flutter_wkwebview: ^3.14.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
