// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS-EMuPCgJBJctjD3-zPULkPUG5ChI2i8',
    appId: '1:942953101996:web:3fa41d46e3e30b6cdc7d09',
    messagingSenderId: '942953101996',
    projectId: 'study-a7154',
    authDomain: 'study-a7154.firebaseapp.com',
    storageBucket: 'study-a7154.appspot.com',
    measurementId: 'G-VPKLPE6QQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1x2gU8Y6kXx1kAvNehzX7fcIsb7i0YC8',
    appId: '1:942953101996:android:e7d64b3e134e1ccbdc7d09',
    messagingSenderId: '942953101996',
    projectId: 'study-a7154',
    storageBucket: 'study-a7154.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRTIHA3wxyyFm1r67SPMDje70w15oxkvg',
    appId: '1:942953101996:ios:80f4b1039d5a846edc7d09',
    messagingSenderId: '942953101996',
    projectId: 'study-a7154',
    storageBucket: 'study-a7154.appspot.com',
    iosBundleId: 'com.sacademy.studyAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRTIHA3wxyyFm1r67SPMDje70w15oxkvg',
    appId: '1:942953101996:ios:80f4b1039d5a846edc7d09',
    messagingSenderId: '942953101996',
    projectId: 'study-a7154',
    storageBucket: 'study-a7154.appspot.com',
    iosBundleId: 'com.sacademy.studyAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS-EMuPCgJBJctjD3-zPULkPUG5ChI2i8',
    appId: '1:942953101996:web:56e635b8786f7a51dc7d09',
    messagingSenderId: '942953101996',
    projectId: 'study-a7154',
    authDomain: 'study-a7154.firebaseapp.com',
    storageBucket: 'study-a7154.appspot.com',
    measurementId: 'G-Q8M4RWR4K3',
  );
}
